title:            Leonardo Zapparoli - Desenvolvimento de software
description:      Um blog sobre Java, Scala, linguagens e relacionados.
url:              
signoff:          Leonardo
disqus_shortname: leonardoz
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-84384831-1

links:
  - name:         Blog
    url:          /
  - name:         Sobre
    url:          /sobre
  - name:         GitHub
    url:          http://github.com/leonardoz
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
