title:            Leonardo Zapparoli - Desenvolvimento de software
description:      Um blog sobre Java, Scala, linguagens e relacionados.
url:              
signoff:          Leonardo
disqus_shortname: leonardoz
facebook_appid:   298713480512281
google_analytics: UA-84384831-1

links:
  - name:         Blog
    url:          /
  - name:         Sobre
    url:          /sobre
  - name:         GitHub
    url:          http://github.com/leonardoz
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge	   
redcarpet:
  extensions:
    - smart
